# Lecture 19


### Olver and Shakiban 4.3 --- using a different method

Lecture notes are available [here](https://drive.google.com/file/d/12DLtoVZjAiF5vnhyuX_Y44W21_QmBCcY/view?usp=sharing).

## Using Householder reflections to put A in upper-triangular form

In [1]:
A = randn(5,3); R = A


R =

    0.5377   -1.3077   -1.3499
    1.8339   -0.4336    3.0349
   -2.2588    0.3426    0.7254
    0.8622    3.5784   -0.0631
    0.3188    2.7694    0.7147



$$ H = I - 2 \frac{ \vec w \vec w^T }{\|\vec w\|_2^2}.$$

$$ H = I - 2 \vec v \vec v^T, \quad \vec v = \frac{\vec w}{\|\vec w\|_2}.$$

In [2]:
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % using (1:end,1:end) is unnecessary
% but it helps to see the pattern


R =

   -3.0983   -0.5473   -1.0892
    0.0000   -0.0501    3.1664
   -0.0000   -0.1297    0.5635
    0.0000    3.7587   -0.0012
    0.0000    2.8361    0.7376



In [3]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end))


R =

   -3.0983   -0.5473   -1.0892
    0.0000    4.7107    0.3939
   -0.0000         0    0.4879
    0.0000   -0.0000    2.1877
    0.0000   -0.0000    2.3892



In [4]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))


R =

   -3.0983   -0.5473   -1.0892
    0.0000    4.7107    0.3939
   -0.0000         0   -3.2760
    0.0000   -0.0000         0
    0.0000   -0.0000         0



At the end of this, $A$ is in upper-triangular form.  This is the $R$ in the $A = QR$ factorization.  That is, we've found a way to apply $Q^T = Q^{-1}$ to $A$ to get $Q^TA = R$.  To understand how to construct $Q$ we have think about what we are doing at each stage.

Start with $Q_0 = I$ and $R_0 = A$.  Then

$$A = Q_0 R_0 = Q_0 H_1^T H_1 R_0$$

where $H_1$ is the Householder reflection constructed based on the first column of $R_0$.  And, we have used that $H_1$ is an orthogonal matrix, $H_1^T H_1 = I$.  But let's look at $H_1$ closer:

In [5]:
R = A;
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
H1 = eye(length(x)) - 2*w*w'


H1 =

   -0.1735   -0.5919    0.7291   -0.2783   -0.1029
   -0.5919    0.7015    0.3677   -0.1404   -0.0519
    0.7291    0.3677    0.5471    0.1729    0.0639
   -0.2783   -0.1404    0.1729    0.9340   -0.0244
   -0.1029   -0.0519    0.0639   -0.0244    0.9910



In [6]:
H1' - H1 % H1 transpose - H1


ans =

     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0



We see that $H_1 = H_1^T$ is symmetric, so that $H_1 = H_1^{-1}$.  This is why these are called reflections.  If you reflect, and reflect again, you should be back where you started.

So, 

$$A = Q_0 R_0 = Q_0 H_1^T H_1 R_0 = (Q_0 H_1) (H_1 R_0)$$.

As before, the following computes $H_1 R_0$ to get $R_1$:

In [7]:
R = A;
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % Applies H1 to R


R =

   -3.0983   -0.5473   -1.0892
    0.0000   -0.0501    3.1664
   -0.0000   -0.1297    0.5635
    0.0000    3.7587   -0.0012
    0.0000    2.8361    0.7376



To compute $Q_0 H_1$, we note that $Q_0$ is the identity matrix:

In [8]:
Q = eye(size(A,1));
Q = Q(:,1:end) - 2*(Q(:,1:end)*w)*w' % Q appears on the left of w, w'
% because Q0 appears to the left of H1


Q =

   -0.1735   -0.5919    0.7291   -0.2783   -0.1029
   -0.5919    0.7015    0.3677   -0.1404   -0.0519
    0.7291    0.3677    0.5471    0.1729    0.0639
   -0.2783   -0.1404    0.1729    0.9340   -0.0244
   -0.1029   -0.0519    0.0639   -0.0244    0.9910



And repeat:

In [9]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end))
% You can do R(2:end,:) = R(2:end,:) - 2*w*(w'*R(2:end,:))
% but we know that most of the first column of R(2:end,:) is zero
% so it makes sense to exclude it from the computation
% But we cannot do that with the rows of Q:
Q(:,2:end) = Q(:,2:end) - 2*(Q(:,2:end)*w)*w'


R =

   -3.0983   -0.5473   -1.0892
    0.0000    4.7107    0.3939
   -0.0000         0    0.4879
    0.0000   -0.0000    2.1877
    0.0000   -0.0000    2.3892


Q =

   -0.1735   -0.2978    0.7371   -0.5105   -0.2781
   -0.5919   -0.1608    0.3442    0.5404    0.4618
    0.7291    0.1574    0.5413    0.3389    0.1892
   -0.2783    0.7273    0.1965    0.2490   -0.5413
   -0.1029    0.5760    0.0810   -0.5201    0.6170



In [10]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))
Q(:,3:end) = Q(:,3:end) - 2*(Q(:,3:end)*w)*w'


R =

   -3.0983   -0.5473   -1.0892
    0.0000    4.7107    0.3939
   -0.0000         0   -3.2760
    0.0000   -0.0000         0
    0.0000   -0.0000         0


Q =

   -0.1735   -0.2978    0.4339   -0.6867   -0.4705
   -0.5919   -0.1608   -0.7489   -0.0949   -0.2321
    0.7291    0.1574   -0.4449   -0.2343   -0.4369
   -0.2783    0.7273    0.1992    0.2506   -0.5396
   -0.1029    0.5760   -0.1147   -0.6339    0.4927



Verify the properties:

In [11]:
A - Q*R % good factorization


ans =

   1.0e-14 *

    0.1443   -0.1110    0.0444
    0.0888    0.0777    0.0444
   -0.0888   -0.0167    0.0888
    0.0111   -0.1776    0.0444
   -0.0111   -0.1332    0.0888



In [12]:
Q'*Q % Q is indeed orthogonal


ans =

    1.0000   -0.0000    0.0000   -0.0000   -0.0000
   -0.0000    1.0000    0.0000   -0.0000         0
    0.0000    0.0000    1.0000   -0.0000   -0.0000
   -0.0000   -0.0000   -0.0000    1.0000   -0.0000
   -0.0000         0   -0.0000   -0.0000    1.0000



In [13]:
Q*Q'


ans =

    1.0000   -0.0000    0.0000   -0.0000    0.0000
   -0.0000    1.0000   -0.0000   -0.0000   -0.0000
    0.0000   -0.0000    1.0000   -0.0000   -0.0000
   -0.0000   -0.0000   -0.0000    1.0000    0.0000
    0.0000   -0.0000   -0.0000    0.0000    1.0000



## Solving a least-squares problem

Find $\vec x$ that minimized

$$ \mathcal L(\vec y) = \| A \vec y - \vec b\|_2^2. $$

In [14]:
A = randn(5,3);  b = ones(5,1);

### By normal equations:

In [15]:
An = A'*A;
bn = A'*b


bn =

    3.9868
    2.3004
    0.9647



In [16]:
x0 = An\bn  % Solves (A'*A)x = A'* b, the normal equations
norm(A*x0-b)  % residual


x0 =

    1.1033
   -0.3527
    1.0275


ans =

    0.6490



In [17]:
R = [A,b];
x = R(1:end,1);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(1:end,1:end) = R(1:end,1:end) - 2*w*(w'*R(1:end,1:end)) % R1


R =

    2.5041    1.6256   -0.5815    1.5921
   -0.0000   -1.1638    0.6528    1.0271
    0.0000    0.1926    0.5853    0.6744
    0.0000    1.1340    1.1345    0.6920
    0.0000   -0.0102    0.0582    0.6902



In [18]:
x = R(2:end,2);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(2:end,2:end) = R(2:end,2:end) - 2*w*(w'*R(2:end,2:end)) % R1


R =

    2.5041    1.6256   -0.5815    1.5921
   -0.0000    1.6363    0.3904   -0.1759
    0.0000         0    0.6033    0.7571
    0.0000         0    1.2407    1.1792
    0.0000         0    0.0572    0.6858



In [19]:
x = R(3:end,3);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(3:end,3:end) = R(3:end,3:end) - 2*w*(w'*R(3:end,3:end))


R =

    2.5041    1.6256   -0.5815    1.5921
   -0.0000    1.6363    0.3904   -0.1759
    0.0000         0   -1.3808   -1.4188
    0.0000         0   -0.0000   -0.1814
    0.0000         0         0    0.6231



In [20]:
x = R(4:end,4);
w = x; w(1) = x(1) + sign(x(1))*norm(x);
w = w/norm(w);
R(4:end,4:end) = R(4:end,4:end) - 2*w*(w'*R(4:end,4:end))


R =

    2.5041    1.6256   -0.5815    1.5921
   -0.0000    1.6363    0.3904   -0.1759
    0.0000         0   -1.3808   -1.4188
    0.0000         0   -0.0000    0.6490
    0.0000         0         0         0



In [21]:
x = Backsub(R(1:3,:))
x0


x =

    1.1033
   -0.3527
    1.0275


x0 =

    1.1033
   -0.3527
    1.0275



In [22]:
x-x0


ans =

   1.0e-15 *

   -0.2220
    0.7772
   -0.4441



In [23]:
abs(R(4,4))
norm(A*x0-b)


ans =

    0.6490


ans =

    0.6490

